export type Categoria = "Todas" | "Pollo" | "Carne" | "Vegano" | "Express" | "Pastas" | "Dulce";

export interface Receta {
  title: string;
  time: string;
  servings: string;
  freezable: boolean;
  tag: Categoria;
  image: string;
  isPremium: boolean;
  ingredients?: string[];
  steps?: string[];
}

export const recetas: Receta[] = [
  {
    title: "Milanesas de pollo con puré",
    time: "40 min",
    servings: "4",
    freezable: true,
    tag: "Pollo",
    image: "/lovable-uploads/b8e7d2b8-bc86-42e1-9376-9a1fc4a5975c.jpg",
    isPremium: false,
    ingredients: [
      "4 pechugas de pollo finas",
      "2 huevos",
      "Pan rallado c/n",
      "Sal y pimienta a gusto",
      "6 papas medianas",
      "50g manteca",
      "Leche c/n",
    ],
    steps: [
      "Salpimentá las pechugas. Pasalas por huevo batido y luego por pan rallado.",
      "Cociná en horno a 200°C por 20 minutos, dando vuelta a mitad de cocción.",
      "Mientras, herví las papas peladas hasta que estén tiernas (20 min aprox).",
      "Pisá las papas, agregá manteca y leche caliente. Mezclá hasta lograr un puré cremoso.",
      "Serví las milanesas doradas acompañadas del puré calentito.",
    ],
  },
  {
    title: "Tarta de zapallitos y queso",
    time: "35 min",
    servings: "6",
    freezable: true,
    tag: "Vegano",
    image: "/lovable-uploads/70e36c43-1f69-4b2b-bfa4-09cb3ad01683.jpg",
    isPremium: false,
    ingredients: [
      "2 tapas de tarta",
      "3 zapallitos rallados",
      "200g queso cremoso",
      "3 huevos",
      "Sal, pimienta, nuez moscada",
      "1 cebolla picada",
    ],
    steps: [
      "Saltéa la cebolla en una sartén hasta que esté transparente.",
      "Agregá los zapallitos rallados y cociná 5 minutos. Dejá enfriar.",
      "Mezclá con los huevos, el queso y los condimentos.",
      "Forrá una tartera con una tapa, volcá el relleno y cubrí con la otra tapa.",
      "Horneá a 180°C por 25-30 minutos hasta que esté dorada.",
    ],
  },
  {
    title: "Pollo al horno con papas",
    time: "55 min",
    servings: "4",
    freezable: false,
    tag: "Pollo",
    image: "/lovable-uploads/f5ae0c21-f49f-41da-8851-58a8fa69a3d0.jpg",
    isPremium: false,
    ingredients: [
      "1 pollo entero o 8 piezas",
      "4 papas grandes cortadas en cubos",
      "3 cdas aceite de oliva",
      "Sal, pimentón, orégano",
      "1 limón",
    ],
    steps: [
      "Precalentá el horno a 200°C.",
      "Condimentá el pollo con sal, pimentón, orégano y jugo de limón.",
      "Distribuí las papas alrededor del pollo en una asadera.",
      "Rociá todo con aceite de oliva.",
      "Horneá 50-55 min hasta que el pollo esté dorado y jugoso.",
    ],
  },
  {
    title: "Nuggets caseros de pollo",
    time: "30 min",
    servings: "6",
    freezable: true,
    tag: "Pollo",
    image: "https://images.unsplash.com/photo-1619221882220-947b3d3c8861?w=600&q=80",
    isPremium: true,
    ingredients: [
      "500g pechuga de pollo",
      "1 huevo",
      "Avena arrollada c/n",
      "1 cdta pimentón dulce",
      "Sal y pimienta a gusto",
      "Spray de aceite de oliva",
    ],
    steps: [
      "Cortá la pechuga en trozos pequeños y salpimentá.",
      "Pasá cada trozo por huevo batido y luego por avena mezclada con pimentón.",
      "Disponé en una placa con papel manteca y rociá con spray de aceite.",
      "Horneá a 200°C por 15-18 min, dando vuelta a mitad de cocción.",
      "Serví con bastones de zanahoria al horno como acompañamiento.",
    ],
  },
  {
    title: "Estofado de carne con verduras",
    time: "60 min",
    servings: "5",
    freezable: true,
    tag: "Carne",
    image: "/lovable-uploads/1e4c3d8b-3d64-451d-829c-1f0931a6621f.webp",
    isPremium: true,
    ingredients: [
      "500g carne para estofado (roast beef o paleta)",
      "2 zanahorias en rodajas",
      "2 papas en cubos",
      "1 cebolla picada",
      "2 tomates perita",
      "1 hoja de laurel",
      "Caldo de verduras c/n",
      "Sal, pimienta, pimentón",
    ],
    steps: [
      "Sellá la carne cortada en cubos en una olla con un hilo de aceite.",
      "Agregá la cebolla y cociná hasta que esté transparente.",
      "Incorporá los tomates procesados, laurel y condimentos.",
      "Sumá zanahorias, papas y caldo hasta cubrir.",
      "Cociná tapado a fuego bajo por 45 min hasta que la carne esté tierna.",
    ],
  },
  {
    title: "Empanadas de carne al horno",
    time: "60 min",
    servings: "12",
    freezable: true,
    tag: "Carne",
    image: "/lovable-uploads/5dbc90f3-f440-4a7a-93d2-59a2ea076f58.png",
    isPremium: true,
    ingredients: [
      "12 tapas de empanadas para horno",
      "400g carne picada magra",
      "2 cebollas picadas",
      "1 morrón rojo",
      "Comino, pimentón, sal",
      "2 huevos duros picados",
      "Aceitunas verdes (opcional)",
    ],
    steps: [
      "Rehogá las cebollas y el morrón hasta que estén tiernos.",
      "Agregá la carne picada y cociná hasta que pierda color rosado.",
      "Condimentá con comino, pimentón y sal. Dejá enfriar.",
      "Mezclá con huevo duro y aceitunas. Rellená las tapas y cerrá con repulgue.",
      "Pintá con huevo batido y horneá a 200°C por 20-25 min hasta dorar.",
    ],
  },
  {
    title: "Hamburguesas caseras completas",
    time: "35 min",
    servings: "4",
    freezable: true,
    tag: "Carne",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80",
    isPremium: true,
    ingredients: [
      "500g carne picada magra",
      "1 cebolla rallada",
      "1 huevo",
      "Pan rallado integral c/n",
      "Sal, pimienta, orégano",
      "4 panes integrales",
      "Lechuga, tomate, queso fresco",
    ],
    steps: [
      "Mezclá la carne con cebolla rallada, huevo, pan rallado y condimentos.",
      "Formá 4 medallones y dejá reposar 10 min en la heladera.",
      "Cociná en plancha o sartén antiadherente 5 min de cada lado.",
      "Tostá los panes en el horno brevemente.",
      "Armá las hamburguesas con lechuga, tomate y queso fresco.",
    ],
  },
  {
    title: "Estofado de lentejas",
    time: "50 min",
    servings: "6",
    freezable: true,
    tag: "Vegano",
    image: "/lovable-uploads/cb281a92-5748-459e-8e6a-9f40ce63f22c.jpg",
    isPremium: true,
    ingredients: [
      "300g lentejas (remojadas si son secas)",
      "1 cebolla picada",
      "2 zanahorias en cubitos",
      "1 papa en cubos",
      "2 tomates perita",
      "1 hoja de laurel",
      "Pimentón, comino, sal",
    ],
    steps: [
      "Rehogá la cebolla en una olla con un poco de aceite.",
      "Agregá zanahorias, papa y tomates procesados.",
      "Incorporá las lentejas escurridas, laurel y condimentos.",
      "Cubrí con agua y cociná a fuego medio-bajo por 35-40 min.",
      "Rectificá la sal y servilo bien calentito.",
    ],
  },
  {
    title: "Tortilla de papas al horno",
    time: "35 min",
    servings: "4",
    freezable: false,
    tag: "Vegano",
    image: "/lovable-uploads/666d6fdb-2c46-4abb-be1e-2ece81e48a06.jpg",
    isPremium: true,
    ingredients: [
      "4 papas medianas en rodajas finas",
      "5 huevos",
      "1 cebolla en juliana",
      "Sal y pimienta",
      "Aceite de oliva c/n",
    ],
    steps: [
      "Horneá las rodajas de papa con un hilo de aceite a 200°C por 15 min.",
      "Saltéa la cebolla hasta que esté dorada.",
      "Batí los huevos con sal y pimienta.",
      "Mezclá papas, cebolla y huevo. Volcá en una sartén apta para horno.",
      "Horneá 15 min a 180°C o hasta que esté firme y dorada.",
    ],
  },
  {
    title: "Pasta con salsa bolognesa",
    time: "45 min",
    servings: "4",
    freezable: true,
    tag: "Pastas",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80",
    isPremium: true,
    ingredients: [
      "400g pasta seca (fusilli o penne)",
      "300g carne picada magra",
      "1 cebolla picada",
      "2 zanahorias ralladas",
      "400ml salsa de tomate natural",
      "Orégano, albahaca, sal",
    ],
    steps: [
      "Rehogá la cebolla y la zanahoria rallada en una sartén.",
      "Agregá la carne y cociná hasta que pierda color rosado.",
      "Incorporá la salsa de tomate y condimentos. Cociná 20 min a fuego bajo.",
      "Mientras, cociná la pasta al dente según las instrucciones del paquete.",
      "Mezclá la pasta con la salsa y serví con albahaca fresca.",
    ],
  },
  {
    title: "Ñoquis de papa caseros",
    time: "50 min",
    servings: "4",
    freezable: true,
    tag: "Pastas",
    image: "/lovable-uploads/c489ce18-16b7-4b89-9ad0-3b924a7adf22.webp",
    isPremium: true,
    ingredients: [
      "1 kg de papas",
      "300g harina 000",
      "1 huevo",
      "Sal y nuez moscada",
      "Salsa fileto o pesto para servir",
    ],
    steps: [
      "Herví las papas con cáscara hasta que estén tiernas. Pelá y pisá.",
      "Agregá el huevo, sal, nuez moscada y la harina de a poco.",
      "Amasá hasta obtener una masa suave. No sobretrabajes.",
      "Formá rollitos y cortá los ñoquis. Marcá con un tenedor.",
      "Cociná en agua hirviendo con sal. Cuando flotan, retiralos y servir con salsa.",
    ],
  },
  {
    title: "Wrap de pollo express",
    time: "15 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/4bea847a-a4c2-4e33-8955-3512cc3df4f9.jpg",
    isPremium: true,
    ingredients: [
      "2 tortillas de trigo",
      "1 pechuga de pollo cocida y desmenuzada",
      "Lechuga, tomate cherry, palta",
      "Queso crema light",
      "Sal, limón, pimienta",
    ],
    steps: [
      "Untá cada tortilla con queso crema.",
      "Distribuí el pollo desmenuzado, lechuga, tomate y palta.",
      "Condimentá con sal, pimienta y un chorrito de limón.",
      "Enrollá bien apretado y cortá al medio.",
      "¡Listo para llevar o comer al instante!",
    ],
  },
  {
    title: "Quesadillas rápidas",
    time: "10 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/bbd10e5a-f7eb-4603-8ef3-ee7c81666b3d.jpg",
    isPremium: true,
    ingredients: [
      "2 tortillas de trigo",
      "100g queso mozzarella rallado",
      "1/2 morrón en tiritas",
      "Hojas de espinaca",
      "Condimento a gusto",
    ],
    steps: [
      "Distribuí queso, morrón y espinaca sobre cada tortilla.",
      "Doblá por la mitad.",
      "Cociná en sartén antiadherente a fuego medio 2-3 min de cada lado.",
      "Cortá en triángulos y servir con ensalada fresca.",
    ],
  },
  {
    title: "Tostadas con huevo y palta",
    time: "10 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/4535cfa5-605f-4a25-9ef6-3803419aca0f.webp",
    isPremium: true,
    ingredients: [
      "2 rebanadas de pan integral",
      "1 palta madura",
      "2 huevos",
      "Sal, pimienta, semillas de sésamo",
      "Jugo de limón",
    ],
    steps: [
      "Tostar el pan hasta que esté crocante.",
      "Pisá la palta con limón, sal y pimienta.",
      "Cociná los huevos a tu gusto (revueltos o poché).",
      "Untá el pan con la palta y colocá el huevo encima.",
      "Espolvoreá con semillas de sésamo y servir.",
    ],
  },
  {
    title: "Budín de pan casero",
    time: "30 min",
    servings: "8",
    freezable: false,
    tag: "Dulce",
    image: "/lovable-uploads/8b1153a5-b702-4d7c-9ac1-ff9c93d9c4a1.webp",
    isPremium: true,
    ingredients: [
      "300g pan del día anterior",
      "500ml leche tibia",
      "3 huevos",
      "100g azúcar",
      "Esencia de vainilla",
      "Pasas de uva (opcional)",
      "Caramelo para el molde",
    ],
    steps: [
      "Remojá el pan en la leche tibia hasta que se deshaga.",
      "Batí los huevos con el azúcar y la vainilla.",
      "Mezclá todo y agregá las pasas si querés.",
      "Volcá en un molde acaramelado.",
      "Horneá a 180°C por 35-40 min a baño maría hasta que esté firme.",
    ],
  },
  {
    title: "Galletitas de avena y banana",
    time: "25 min",
    servings: "20",
    freezable: true,
    tag: "Dulce",
    image: "/lovable-uploads/e9035ab4-cc26-4711-b767-9750ea572112.webp",
    isPremium: true,
    ingredients: [
      "2 bananas maduras",
      "150g avena arrollada",
      "2 cdas miel o endulzante",
      "Canela a gusto",
      "Chips de chocolate (opcional)",
      "1 cda aceite de coco",
    ],
    steps: [
      "Pisá las bananas hasta hacer un puré.",
      "Mezclá con la avena, miel, canela y aceite de coco.",
      "Agregá chips de chocolate si querés.",
      "Formá bolitas y aplastá sobre una placa con papel manteca.",
      "Horneá a 180°C por 15-18 min hasta que estén doradas.",
    ],
  },
];

export const categorias: { label: Categoria; icon: string }[] = [
  { label: "Todas", icon: "UtensilsCrossed" },
  { label: "Pollo", icon: "Drumstick" },
  { label: "Carne", icon: "Beef" },
  { label: "Vegano", icon: "Salad" },
  { label: "Express", icon: "Zap" },
  { label: "Pastas", icon: "UtensilsCrossed" },
  { label: "Dulce", icon: "CakeSlice" },
];
