export type Categoria = "Todas" | "Pollo" | "Carne" | "Vegano" | "Express" | "Pastas" | "Dulce";

export interface Receta {
  title: string;
  time: string;
  servings: string;
  freezable: boolean;
  tag: Categoria;
  image: string;
  isPremium: boolean;
  ingredients?: string[];
  steps?: string[];
}

export const recetas: Receta[] = [
  {
    title: "Milanesas de pollo con puré",
    time: "40 min",
    servings: "4",
    freezable: true,
    tag: "Pollo",
    image: "/lovable-uploads/b8e7d2b8-bc86-42e1-9376-9a1fc4a5975c.jpg",
    isPremium: false,
    ingredients: [
      "4 pechugas de pollo finas",
      "2 huevos",
      "Pan rallado c/n",
      "Sal y pimienta a gusto",
      "6 papas medianas",
      "50g manteca",
      "Leche c/n",
    ],
    steps: [
      "Salpimentá las pechugas. Pasalas por huevo batido y luego por pan rallado.",
      "Cociná en horno a 200°C por 20 minutos, dando vuelta a mitad de cocción.",
      "Mientras, herví las papas peladas hasta que estén tiernas (20 min aprox).",
      "Pisá las papas, agregá manteca y leche caliente. Mezclá hasta lograr un puré cremoso.",
      "Serví las milanesas doradas acompañadas del puré calentito.",
    ],
  },
  {
    title: "Tarta de zapallitos y queso",
    time: "35 min",
    servings: "6",
    freezable: true,
    tag: "Vegano",
    image: "/lovable-uploads/70e36c43-1f69-4b2b-bfa4-09cb3ad01683.jpg",
    isPremium: false,
    ingredients: [
      "2 tapas de tarta",
      "3 zapallitos rallados",
      "200g queso cremoso",
      "3 huevos",
      "Sal, pimienta, nuez moscada",
      "1 cebolla picada",
    ],
    steps: [
      "Saltéa la cebolla en una sartén hasta que esté transparente.",
      "Agregá los zapallitos rallados y cociná 5 minutos. Dejá enfriar.",
      "Mezclá con los huevos, el queso y los condimentos.",
      "Forrá una tartera con una tapa, volcá el relleno y cubrí con la otra tapa.",
      "Horneá a 180°C por 25-30 minutos hasta que esté dorada.",
    ],
  },
  {
    title: "Pollo al horno con papas",
    time: "55 min",
    servings: "4",
    freezable: false,
    tag: "Pollo",
    image: "/lovable-uploads/f5ae0c21-f49f-41da-8851-58a8fa69a3d0.jpg",
    isPremium: false,
    ingredients: [
      "1 pollo entero o 8 piezas",
      "4 papas grandes cortadas en cubos",
      "3 cdas aceite de oliva",
      "Sal, pimentón, orégano",
      "1 limón",
    ],
    steps: [
      "Precalentá el horno a 200°C.",
      "Condimentá el pollo con sal, pimentón, orégano y jugo de limón.",
      "Distribuí las papas alrededor del pollo en una asadera.",
      "Rociá todo con aceite de oliva.",
      "Horneá 50-55 min hasta que el pollo esté dorado y jugoso.",
    ],
  },
  {
    title: "Nuggets caseros de pollo",
    time: "30 min",
    servings: "6",
    freezable: true,
    tag: "Pollo",
    image: "https://images.unsplash.com/photo-1619221882220-947b3d3c8861?w=600&q=80",
    isPremium: true,
  },
  {
    title: "Estofado de carne con verduras",
    time: "60 min",
    servings: "5",
    freezable: true,
    tag: "Carne",
    image: "/lovable-uploads/1e4c3d8b-3d64-451d-829c-1f0931a6621f.webp",
    isPremium: true,
  },
  {
    title: "Empanadas de carne al horno",
    time: "60 min",
    servings: "12",
    freezable: true,
    tag: "Carne",
    image: "/lovable-uploads/5dbc90f3-f440-4a7a-93d2-59a2ea076f58.png",
    isPremium: true,
  },
  {
    title: "Hamburguesas caseras completas",
    time: "35 min",
    servings: "4",
    freezable: true,
    tag: "Carne",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&q=80",
    isPremium: true,
  },
  {
    title: "Estofado de lentejas",
    time: "50 min",
    servings: "6",
    freezable: true,
    tag: "Vegano",
    image: "/lovable-uploads/cb281a92-5748-459e-8e6a-9f40ce63f22c.jpg",
    isPremium: true,
  },
  {
    title: "Tortilla de papas al horno",
    time: "35 min",
    servings: "4",
    freezable: false,
    tag: "Vegano",
    image: "/lovable-uploads/666d6fdb-2c46-4abb-be1e-2ece81e48a06.jpg",
    isPremium: true,
  },
  {
    title: "Pasta con salsa bolognesa",
    time: "45 min",
    servings: "4",
    freezable: true,
    tag: "Pastas",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=600&q=80",
    isPremium: true,
  },
  {
    title: "Ñoquis de papa caseros",
    time: "50 min",
    servings: "4",
    freezable: true,
    tag: "Pastas",
    image: "/lovable-uploads/c489ce18-16b7-4b89-9ad0-3b924a7adf22.webp",
    isPremium: true,
  },
  {
    title: "Wrap de pollo express",
    time: "15 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/4bea847a-a4c2-4e33-8955-3512cc3df4f9.jpg",
    isPremium: true,
  },
  {
    title: "Quesadillas rápidas",
    time: "10 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/bbd10e5a-f7eb-4603-8ef3-ee7c81666b3d.jpg",
    isPremium: true,
  },
  {
    title: "Tostadas con huevo y palta",
    time: "10 min",
    servings: "2",
    freezable: false,
    tag: "Express",
    image: "/lovable-uploads/4535cfa5-605f-4a25-9ef6-3803419aca0f.webp",
    isPremium: true,
  },
  {
    title: "Budín de pan casero",
    time: "30 min",
    servings: "8",
    freezable: false,
    tag: "Dulce",
    image: "/lovable-uploads/8b1153a5-b702-4d7c-9ac1-ff9c93d9c4a1.webp",
    isPremium: true,
  },
  {
    title: "Galletitas de avena y banana",
    time: "25 min",
    servings: "20",
    freezable: true,
    tag: "Dulce",
    image: "/lovable-uploads/e9035ab4-cc26-4711-b767-9750ea572112.webp",
    isPremium: true,
  },
];

export const categorias: { label: Categoria; icon: string }[] = [
  { label: "Todas", icon: "UtensilsCrossed" },
  { label: "Pollo", icon: "Drumstick" },
  { label: "Carne", icon: "Beef" },
  { label: "Vegano", icon: "Salad" },
  { label: "Express", icon: "Zap" },
  { label: "Pastas", icon: "UtensilsCrossed" },
  { label: "Dulce", icon: "CakeSlice" },
];
